apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: deny-writes
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchPaths:
      - path: "/etc/*"
        action: Block
