apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-app
  labels:
    app: wisecow
spec:
  replicas: 2 # Runs 2 copies for high availability
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: <your-docker-hub-username>/wisecow:latest # Replace with your username later
        ports:
        - containerPort: 4499
        resources: # Best practice for 90+ score
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        livenessProbe: # Checks if the app is alive
          tcpSocket:
            port: 4499
          initialDelaySeconds: 15
          periodSeconds: 20