apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: hawaldarshivani/wisecow:latest
        imagePullPolicy: Always   # <-- added
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007
