name: Wisecow CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build . -t wisecow-app:latest
          echo "Docker image built successfully"

      - name: Validate Kubernetes Manifests
        run: |
          # This checks if your YAML files are formatted correctly
          # without needing a live connection to a cluster
          kubectl apply --dry-run=client -f k8s/
          echo "All manifests in k8s/ folder are valid."