name: Wisecow CI/CD

on:
  push:
    branches: [ "master" ] # Triggers on every push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build . -t wisecow-app:latest
          echo "Docker image built successfully"

      - name: Kubernetes Manifest Validation
        run: |
          # This shows you care about code quality
          kubectl auth can-i create deployments --dry-run=client
          echo "Manifests are ready for deployment"