name: Wisecow CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build . -t wisecow-app:latest
          echo "Docker build successful!"

      - name: Verify Manifests Exist
        run: |
          # This simply checks if your files are in the right place
          ls -R k8s/
          ls scripts/
          echo "Project structure verified."